### PR TITLE
QuNetSim changes to enable simulation of non-ideal networks

### PR DESCRIPTION
**Pull request by AnirbanHFX**
This version of QuNetSim is backward compatible with any program written for the original, to the best of my knowledge.

It incorporates the following parameters for simulation non-ideal networks -

1. Transmission probability of qubits and EPR signals based on channel length and absorption coefficient - Quantum connections are treated as objects which contain these parameters. Transmission probability checking is handled in the _process_queue of the network.

2. Heralding Probability, Reading Efficiency and Coherence Time have been added as parameters of the Quantum Storage object and can be set or accessed from the host. Coherence Time is based on 'ticks' of the network.

3. Fidelity has been added as a property of a qubit which is used specifically during EPR pair generation. Entangled qubits are programmed to have the same fidelity. Fidelity is updated during entanglement swap. [Possible Future Changes : Fidelity could be made a property of an EPR pair as an object instead of the individual qubits]

4. Classical connections are treated as objects. In addition to receiver_id, they include distance which can be used to calculate time required for transmission of a packet.

5. 'Ticks' have been added to the network. Ticks can be used for estimating simulation time. It is specifically used for simulating decoherence of qubits in the storage. Ticks are correlated with time based on the property 'tickspan' which is the span of virtual time in seconds between two ticks. Ticks are incremented in the _process_queue of the network whenever a packet is transmitted, based on the length of the connection over which it is transmitted 
`(time = distance/speed of light; 
ticks = time/tickspan)`

### CODE REVIEW

**Comment by stephendiadamo** [comment]
Before reviewing this pull request, could you ensure that there are no merge conflicts?

**Comment by AnirbanHFX** [comment]
Resolved conflicts.

Note: Default backend has been changed to CQCBackend in this fork. This may be changed back to EQSN if required.

**Comment by stephendiadamo** [comment]
Yes, please change it back to EQSN. EQSN is our main backend, so things should work in that environment to be merged.

Moreover, before integrating any changes on the master branch, there's the requirement that any added features require a test case added as well, as long as the outputs aren't too randomized. Adding documentation would also be very helpful.

In the `integration_tests` folder is where the tests should be added.

**Comment by stephendiadamo** [comment]
@HalcyonicFalconX In order to break this pull request into smaller pieces (which we will discuss tomorrow) I'm going to add you as a contributor to the project and we can organize the pieces using the Project part of Github for QuNetSim. Then we can better organize the progress. I'll keep this pull request open for now, but will close it later so that we can work with contributing feature by feature.

**Comment by stephendiadamo** [comment]
I'm going to close this pull request since we are breaking it down into smaller parts.

**Pull request closed without merging**
